@echo off
echo Setting Java Path..
set path="C:\Program Files\Java\jdk1.7.0_25\bin"
echo Java Path is set...
echo Compiling 'KeyMethodMapV1.java'...
javac -d . lib/KeyMethodMapV1.java
echo Compiling 'ExportTableV1.java'...
javac -d . -classpath lib\jdom-1.0.jar;lib\poi-3.0-rc4-20070503.jar;lib\ojdbc14.jar;lib\mysql-connector-java-5.1.6.jar; lib/ExportTableV1.java
echo Compiling 'ExportExcelV1.java'...
javac -d . -classpath lib\jdom-1.0.jar;lib\poi-3.0-rc4-20070503.jar;lib\ojdbc14.jar;lib\mysql-connector-java-5.1.6.jar; lib/ExportExcelV1.java
echo Running 'ExportExcelV1.class'...
java -classpath lib\jdom-1.0.jar;lib\poi-3.0-rc4-20070503.jar;lib\ojdbc14.jar;lib\mysql-connector-java-5.1.6.jar; lib/ExportExcelV1
pause

